version: "3.8"
services:
  nlp-service:
    container_name: "nlp-service-${ENV:-development}"
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /opt/app/src
    volumes:
      - "./:/opt/app"
    env_file: ./environment/.env.development
   

    